services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs       
    command:
      --ssl
      --sslcert /certs/localhost.crt
      --sslkey /certs/localhost.key
    ports:
      - 9443:9443
      - 8080:8000
    networks:
      - portainer  
networks:
  portainer:
volumes:
  portainer_data:
